name: Selenium Tests in GitHub Runner

on:
  push:
    branches:
      - master
    # Trigger workflow when pushing to master branch with changes to files under these directories
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'test-suites/**'
  workflow_dispatch:
    inputs:
      run_browser:
        description: 'Pick a browser to run tests on'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Edge
          - Firefox
  # Cron jobs run in UTC by default in GitHub Actions
  schedule:
    - cron: '0 0 10 * *'  # Runs at midnight UTC on the 10th of every month (Chrome)
    - cron: '0 0 20 * *'  # Runs at midnight UTC on the 20th of every month (Edge)
    - cron: '0 0 30 * *'  # Runs at midnight UTC on the 30th of every month (Firefox)

jobs:
  test:
    # Manually skip tests by including "/djd skip tests" in commit message. Useful when making changes to comments
    if: "!contains(github.event.head_commit.message, '/djd skip tests')"

    # The ubuntu-latest image comes with multiple things pre-installed so don't have to install them in this yaml file
    # Maven, Java 17, Chrome, Edge, and Firefox browsers
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # $GITHUB_ENV is a file used by GitHub Actions. Key-value pairs are appended (>>) to it to define env variables
      # 1st if statement executes if github.event.inputs.run_browser is NOT NULL (On manual input from GitHub website)
      # $(date +%d) function in 2nd-4th if statements returns the day as a two digit number (Cron schedule)
      # Default behavior is to run tests on Chrome (On code push)
      - name: Set browser
        run: |
          if [[ -n "${{ github.event.inputs.run_browser }}" ]]; then
            echo "BROWSER=${{ github.event.inputs.run_browser }}" >> $GITHUB_ENV
          elif [[ "$(date +%d)" == "10" ]]; then
            echo "BROWSER=Chrome" >> $GITHUB_ENV
          elif [[ "$(date +%d)" == "20" ]]; then
            echo "BROWSER=Edge" >> $GITHUB_ENV
          elif [[ "$(date +%d)" == "30" ]]; then
            echo "BROWSER=Firefox" >> $GITHUB_ENV
          else
            echo "BROWSER=Chrome" >> $GITHUB_ENV
          fi

      - name: Run tests with Maven
        run: mvn clean test -Denv=PRD -Dbrowser=$BROWSER -DtestSuite=DJDSuite.xml -Durl=https://www.rahulshettyacademy.com/loginpagePractise/

      - name: Upload HTML Results Report
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results/*.html # Match and upload any HTML file under the test-results directory