name: Selenium Tests in GitHub Runner

on:
  # Trigger workflow when pushing to specific branch with changes to files under specific directories
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'test-suites/**'

  # Trigger workflow manually from GitHub website
  workflow_dispatch:
    inputs:
      run_browser:
        description: 'Pick a browser to run tests on'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Edge
          - Firefox

  # Configure workflow to run on a schedule. Cron jobs run in UTC by default in GitHub Actions
  # Runs on repo's default branch (master)
  schedule:
    - cron: '40 2 21 * *'  # Runs at 8 AM UTC (2 AM CST) on the 10th of every month (Chrome)
    - cron: '0 8 20 * *'  # Runs at 8 AM UTC (2 AM CST) on the 20th of every month (Edge)
    - cron: '0 8 30 * *'  # Runs at 8 AM UTC (2 AM CST) on the 30th of every month (Firefox)

jobs:
  test:
    # Manually skip tests by including "/djd skip tests" in commit message. Useful when making changes to comments
    if: "!contains(github.event.head_commit.message, '/djd skip tests')"

    # The ubuntu-latest image comes with multiple things pre-installed so don't have to install them as part of this yaml file
    # Maven, Java 17, Chrome, Edge, and Firefox browsers come pre-installed
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # $GITHUB_ENV is a file used by GitHub Actions. Key-value pairs are appended (>>) to it to define env variables
      # $GITHUB_ENV persists across all steps in a given job
      # 1st if-statement executes if github.event.inputs.run_browser is NOT NULL (On manual input from GitHub website)
      # $(date +%d) function in 2nd-4th if-statements returns the day as a two digit number (Cron schedule)
      # Default behavior is to run tests on Chrome (On code push)
      - name: Set browser
        run: |
          if [[ -n "${{ github.event.inputs.run_browser }}" ]]; then
            echo "BROWSER=${{ github.event.inputs.run_browser }}" >> $GITHUB_ENV
          elif [[ "$(date +%d)" == "10" ]]; then
            echo "BROWSER=Chrome" >> $GITHUB_ENV
          elif [[ "$(date +%d)" == "20" ]]; then
            echo "BROWSER=Edge" >> $GITHUB_ENV
          elif [[ "$(date +%d)" == "30" ]]; then
            echo "BROWSER=Firefox" >> $GITHUB_ENV
          else
            echo "BROWSER=Chrome" >> $GITHUB_ENV
          fi

      # The "$?" part is a special shell variable that holds the exit code of the last executed command
      # Exit code is 0 when tests pass and non-zero otherwise
      - name: Run tests with Maven and store exit code
        run: |
          echo "Starting tests on: $BROWSER"
          mvn clean test -Denv=PRD -Dbrowser=$BROWSER -DtestSuite=DJDSuite.xml -Durl=https://www.rahulshettyacademy.com/loginpagePractise/
          echo "MVN_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Upload HTML results report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results/*.html # Match and upload any HTML file under the test-results directory

      - name: Download HTML results report for later use
        uses: actions/download-artifact@v4
        with:
          name: Test Results

      # Have to create and use app password instead of regular password to authenticate
      # https://support.google.com/accounts/answer/185833?visit_id=638748503085955270-2173767296&p=InvalidSecondFactor&rd=1
      # Have to use env.MVN_EXIT_CODE with ${{ .. }} because shell varibles (like $MVN_TEST_CODE) only work inside run steps
      # ${{ env.MVN_EXIT_CODE == '0' && 'PASSED' || 'FAILED' }} is like ternary operator. Evaluates to PASSED when exit code is 0 and FAILED otherwise
      - name: Send email after SCHEDULED runs
        if: github.event_name == 'schedule'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_APP_PASSWORD }}
          subject: "GitHub Actions: Test Run Results on $BROWSER (${{ env.MVN_EXIT_CODE == '0' && 'PASSED' || 'FAILED' }})"
          body: | 
            Scheduled test run on $BROWSER has completed. 
          
            Status: ${{ env.MVN_EXIT_CODE == '0' && 'PASSED' || 'FAILED' }}
          
            See results at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          #html_body: file://test-results/*.html
          to: "davidjdang81@gmail.com"
          from: "GitHub Actions"
          attachments: test-results/*.html
